[package]
name = "swiss_village_registery"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rutie = "0.8.2"

[lib]
name = "swiss_village_registery"
crate-type = ["cdylib"]
